version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=7777
      - COUCHDB_URL=http://admin:sikrit@db:5984
    ports:
      - 7777:7777
  db:
    image: couchdb:1.7.1
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=sikrit
